### ISSUE TITLE
app-vim/youcompleteme upstream changed again

### ISSUE THREAD

**Issue by Universebenzene** [ahyangyi/ahyangyi-overlay#5]
又是我来了……ycm上游把third_party下的pythonfutures[移除](https://github.com/ycm-core/YouCompleteMe/commit/154cfb2f0745b8323813a7137911cdd702349b5f)了，于是ebuild 59行报错，看来又需要修改了

**Comment by Universebenzene** [comment]
又有新状况……python-single-r1.eclass也改了新东西，PYTHON_USEDEP deprecated了，DEPEND和RDEPEND也要改……

**Comment by Universebenzene** [comment]
自己试着改了下，补全python不行了，log里是这样：
```
Traceback (most recent call last):
  File "/usr/share/vim/vimfiles/third_party/ycmd/ycmd/handlers.py", line 121, in GetCompletions
    completions = filetype_completer.ComputeCandidates( request_data )
  File "/usr/share/vim/vimfiles/third_party/ycmd/ycmd/completers/completer.py", line 280, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/usr/share/vim/vimfiles/third_party/ycmd/ycmd/completers/completer.py", line 293, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/usr/share/vim/vimfiles/third_party/ycmd/ycmd/completers/python/python_completer.py", line 186, in ComputeCandidatesInner
    completions = self._GetJediScript( request_data ).complete( line, column )
AttributeError: 'Script' object has no attribute 'complete'
```

看来ycm是真难打包啊……

=======
大概乱查了下，好像是最新的ycm要求jedi得到0.16以上？portage里还没这么新的版本……暂时只能先改ebuild限制到417b74b那个commit了……
